apiVersion: apps/v1
kind: Deployment
metadata:
  name: vproapp
spec:
  selector:
    matchLabels:
      app: vproapp
  template:
    metadata:
      labels:
        app: vproapp
    spec:
      containers:
      - name: vproapp
        image: 25795/vproapp:v1
        ports:
        - containerPort: 8080
          name: vproapp-port
      initContainers:
      - name: waitfordb
        image: busybox
        command: ['sh', '-c', 'until nslookup db01.vprofile.svc.cluster.local; do echo waiting for database; sleep 2; done;']
      - name: waitforcache
        image: busybox
        command: ['sh', '-c', 'until nslookup mc01.vprofile.svc.cluster.local; do echo waiting for memcached; sleep 2; done;']